ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  name: cloud-foundry
  prefix: cap.type.platform
  displayName: Cloud Foundry Platform
  description: This Type indicates that a given platform is a Cloud Foundry installation.
  documentationURL: https://capact.io
  supportURL: https://capact.io
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
  attributes:
    cap.core.attribute.system.baseline:
      revision: 0.1.0
spec:
  additionalRefs:
    - cap.core.type.platform
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The Cloud Foundry configuration",
        "required": [
          "version"
        ],
        "definitions": {
          "semVer": {
            "type": "string",
            "minLength": 5,
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
            "title": "Semantic Versioning version",
            "examples": [
              "1.19.0",
              "2.0.1-alpha1"
            ]
          }
        },
        "properties": {
          "version": {
            "$ref": "#/definitions/semVer"
          }
        },
        "additionalProperties": true
      }
