ocfVersion: 0.0.1
revision: 0.1.0
kind: Type
metadata:
  prefix: "cap.type.database.object.aws.s3"
  name: config
  displayName: Config for AWS S3
  description: Config for AWS S3 object store
  documentationURL: https://aws.amazon.com/s3/
  supportURL: https://aws.amazon.com/s3/
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io
spec:
  jsonSchema:
    value: |-
      {
        "$schema": "http://json-schema.org/draft-07/schema",
        "type": "object",
        "title": "The schema for MinIO installation input",
        "examples": [
          {
            "endpoint": "https://minio.default.svc.cluster.local",
            "accesskey": "foo",
            "secretkey": "bar"
          }
        ],
        "required": [
           "name"
        ],
        "properties": {
          "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "Defines a cluster name for the MinIO"
          },
          "accesskey": {
            "$id": "#/properties/accesskey",
            "type": "string",
            "title": "Defines MinIO access Key"
          },
          "secretkey": {
            "$id": "#/properties/secretkey",
            "type": "string",
            "title": "Defines MinIO secret Key"
          }
        },
        "additionalProperties": false
      }
