ocfVersion: 0.0.1
revision: 0.1.0
kind: Interface
metadata:
  prefix: cap.interface.productivity.rocketchat
  name: install
  displayName: "Install"
  description: "Install action for Rocket.Chat"
  documentationURL: https://docs.rocket.chat/
  supportURL: https://rocket.chat/
  iconURL: https://528977-1685022-raikfcquaxqncofqfm.stackpathdns.com/assets/img/header/logo.svg
  maintainers:
    - email: team-dev@capact.io
      name: Capact Dev Team
      url: https://capact.io

spec:
  input:
    parameters:
      input-parameters:
        typeRef:
          path: cap.type.productivity.rocketchat.install-input
          revision: 0.1.0

  output:
    typeInstances:
      rocketchat-config:
        typeRef:
          path: cap.type.productivity.rocketchat.config
          revision: 0.1.0
